ARG NODE_VERSION=22.13.1

FROM node:${NODE_VERSION}-slim AS base
USER node
WORKDIR /home/node
COPY --chown=node:node package*.json ./

FROM base AS development
USER node
WORKDIR /home/node
RUN npm ci --include=dev
COPY --chown=node:node . .
CMD [ "npm", "run", "serve" ]
